# Generated by Django 5.2.6 on 2025-09-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_spot_amala_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_urls', to='places.candidate')),
            ],
        ),
    ]
