# Generated by Django 5.2.6 on 2025-09-14 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0003_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='photourl',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='photourl',
            name='content_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photourl',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
