# Generated by Django 5.2.6 on 2025-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_candidate_email_candidate_hours_text_candidate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='spot',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
