# Generated by Django 5.2.6 on 2025-09-12 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_candidate_open_hours_alter_candidate_price_band_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='payload',
        ),
        migrations.AddField(
            model_name='submission',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='submission',
            name='country',
            field=models.CharField(default='Nigeria', max_length=120),
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='submission',
            name='hours_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('agentic', 'Agentic')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='submission',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='price_band',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='submission',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
