# Generated by Django 5.2.6 on 2025-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
